spring:
  profiles.default: default
---
spring:
  config:
    activate:
      on-profile: default
  cloud:
    config:
      enabled: false

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    batch-replication: true
---
spring:
  config:
    activate:
      on-profile: ds9

eureka:
  instance:
    hostname: eureka.justjournal.com
  client:
    serviceUrl:
      defaultZone: http://appstore.midnightbsd.org:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: appstore

eureka:
  instance:
    hostname: appstore.midnightbsd.org
  client:
    serviceUrl:
      defaultZone: http://eureka.justjournal.com:8761/eureka/